# Introduction to Data Science 2025

# Week 1

## Exercise 1 | Matrix warm-up
<span style="background-color: #ccfff2"> *Note: You can find tutorials for NumPy and Pandas under 'Useful tutorials' in the course material.*</span>

One of the most useful properties of any scientific programming language (Python with NumPy, R, Julia, etc) is that they allow us to work with matrices efficiently. Let's learn more about these features!

### 1.1 Basics

1. Let's start by creating two arrays <span style="background-color: #ccfff2"> A</span> and <span style="background-color: #ccfff2"> B</span> which each have the integers <span style="background-color: #ccfff2"> 0, 1, 2, ..., 1e7-1</span>. Use the normal arrays or lists of the programming language you are using, e.g. *list* or *[ ]* or *numpy.array()* in Python.

In [24]:
import numpy as np

A = np.arange(10000000-1)
B = np.arange(10000000-1)

2. Create a function that uses a <span style="background-color: #ccfff2"> for loop</span> or equivalent to return a new array <span style="background-color: #ccfff2"> C</span>, which contains the <span style="background-color: #ccfff2"> element-wise sum of *A* and *B*</span>, e.g. C should contain the integers <span style="background-color: #ccfff2"> 0, 2, 4, etc</span>.

In [21]:

def add_with_for(A,B):
    C = []
    # add your code here
    maxlen = max(len(A),len(B))
    for i in range(maxlen):
        valA = 0
        valB = 0
        if(i < len(A)):
            valA = A[i]
        if(i < len(B)):
            valB = B[i]
        val = valA + valB
        C.append(val)
    return C

3. Next, let's create another function that uses NumPy (or equivalent) to do the same. To try it out, allocate two arrays (e.g. using <span style="background-color: #ccfff2"> np.array</span> in NumPy) and add the arrays together using your function. Don't use loops, instead, find out how to add the two arrays directly. What do you notice in comparison to the previous function?

In [28]:
# Use this cell for your code
A = np.arange(10000000-1)
B = np.arange(10000000-1)
# C = add_with_for(A,B)     4s116ms
C = A+B                    # 182ms so fast


### 1.2 Array manipulation

<span style="background-color: #ccfff2"> *Note: for the following exercises, only use NumPy or equivalent functions. Don't use any loops.* </span>
1. Create the following array:

*[hint: <span style="background-color: #ccfff2"> np.reshape</span>]*

In [25]:
# array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
#        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
#        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
#        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
#        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
#        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
#        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
#        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [33]:
# Use this cell for your code
array = np.arange(100)
newArray = array.reshape((10,10))
print(newArray)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


2. Create the following array:

In [27]:
# array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [35]:
# Use this cell for your code
array = np.arange(100)
newArray = array.reshape((10,10))
newArray = newArray%2
print(newArray)

[[0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1 0 1]]


3. Create the following array (D):

In [29]:
# array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [42]:
# Use this cell for your code
D = np.ones((10,10))
np.fill_diagonal(D,0)
print(D)

[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]]


4. Create the following array (E):

In [31]:
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [47]:
# Use this cell for your code
E = np.ones((10,10))
x = np.arange(10)
y = np.arange(9,-1,-1)
E[x,y] = 0
print(E)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5. Call the last two matrices <span style="background-color: #ccfff2">D</span> and <span style="background-color: #ccfff2">E</span>, respectively. Show that the determinant of their product (matrix multiplication) is the same as the product of their determinants. That is calculate both <span style="background-color: #ccfff2">det(DE)</span> and <span style="background-color: #ccfff2">det(D) * det(E)</span>, and show that they are the same. Is it a coincidence? (I think not) The product of the determinants (or the determinant of the product) should be -81.

In [50]:
# Use this cell for your code
det_D = np.linalg.det(D)
det_E = np.linalg.det(E)
det_DE = np.linalg.det(D@E)
det_D_E = det_D*det_E
print(det_DE)
print(det_D_E)

-81.0000000000001
-81.0


-- *Use this markdown cell for your written answer* --

### 1.3 Slicing

Array slicing is a powerful way to extract data from an array. Let's practice array slicing with the following exercises!

1. Load the [California housing dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html). The data should be a matrix of shape <span style="background-color: #ccfff2">(20640, 8)</span>, that is 20640 rows and 8 columns. Use the <span style="background-color: #ccfff2">.shape</span> attribute of NumPy arrays to verify this. Here's a [description of the fields](https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset).

In [20]:
import sklearn

# Use this cell for your code

california_housing_data = sklearn.datasets.fetch_california_housing().data
print(california_housing_data.shape)
print(california_housing_data[0])

(20640, 8)
[   8.3252       41.            6.98412698    1.02380952  322.
    2.55555556   37.88       -122.23      ]


2. Select rows where the average number of bedrooms <span style="background-color: #ccfff2">(AveBedrms)</span> is higher than 2. The first few row indices should be <span style="background-color: #ccfff2">710,  1023,  1024, ...</span> (zero-indexed). Count these houses - how many rows are selected? *[hint: <span style="background-color: #ccfff2">np.where</span>]*

In [27]:
# Use this cell for your code
import numpy as np
ave_bedrms = california_housing_data[:, 3]
indices = np.where(ave_bedrms > 2)[0]

print(indices[:5])
print("the number of rows", len(indices))

[ 710 1023 1024 1030 1102]
the number of rows 235


3. Select the rows where the median house age (i.e. median in each block group) <span style="background-color: #ccfff2">(HouseAge)</span> is between 1 and 3 years (inclusive). There should be **124** of these.

In [30]:
# Use this cell for your code
house_age = california_housing_data[:,1]
indices = np.where((house_age >= 1) & (house_age <= 3))[0]

print("the number of rows", len(indices))

the number of rows 124


4. Find the mean of the block group population <span style="background-color: #ccfff2">(Population)</span> for homes whose median value is more than 25000 USD (the target variable). It should be around **1425.68**.

In [38]:
# Use this cell for your code
california_housing = sklearn.datasets.fetch_california_housing()

population = california_housing.data[:, 4]
median_value = california_housing.target

indices = np.where(median_value > 0.25)[0]

mean_population = population[indices].mean()

print("the mean of population:", mean_population)

the mean of population: 1425.6833737275813


## Exercise 2 | Working with text data

Next, let's look into some text data. We will be looking into Amazon reviews, and the necessary steps to transform a raw dataset into a format more suitable for prediction tasks.

1. Download the automotive 5-core dataset from [here](https://jmcauley.ucsd.edu/data/amazon_v2/categoryFilesSmall/Automotive_5.json.gz). Next, you can extract the data in <span style="background-color: #ccfff2">JSON</span> format. You can also download one of the bigger ones, if you are feeling ambitious. Open the JSON file. Access the <span style="background-color: #ccfff2">reviewText</span> field, which contains the unstructured review text written by the user.

For instance, the first review reads as follows: 

*'After I wrote the below review, the manufacturer contacted me and explained how to use this.  Instead of the (current) picture on Amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally. [...]'*

In [14]:
import json

data = []
with open('Automotive_5.json', 'r', encoding='utf-8') as f:
    for line in f:
        line = line.strip()
        line = json.loads(line)
        reviewText = line.get("reviewText")
        if reviewText is not None:
            data.append(reviewText)
print(data[0])

After I wrote the below review, the manufacturer contacted me and explained how to use this.  Instead of the (current) picture on Amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.  Then the charge / sync cable goes through the hole and you can charge from the side.  When used in landscape position this stand does make more sense so I'm upgrading this review from 2 stars to 4 stars (which I rarely do, but in this case user error) with a star off for lack of documentation.  Manufacturer has said he will include directions and I would also encourage him to update the photos on Amazon with more examples of how this can be used.  The wood quality is indeed good and it's a sturdy little stand.  I'm trying to think of when I'd actually use this stand... perhaps for Facetime chats.  I also think it would be useful for someone in an open office environment if they want to keep their phone on their desk and see alerts / notifications easi

2. Next, let's follow some steps to normalize the text data.

When dealing with natural language, it is important to notice that while, for example, the words "Copper" and "copper" are represented by two different strings, they have the same meaning. When applying statistical methods on this data, it is useful to ensure that words with the same meaning are represented by the same string.

* <span style="background-color: #ccfff2">Downcasing</span>: Let's first downcase the contents of the <span style="background-color: #ccfff2">reviewText</span> field.

Now the first review should be:

*'after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.'*

In [15]:
# Use this cell for your code
data = [s.lower() for s in data]
print(data[0])

after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.  then the charge / sync cable goes through the hole and you can charge from the side.  when used in landscape position this stand does make more sense so i'm upgrading this review from 2 stars to 4 stars (which i rarely do, but in this case user error) with a star off for lack of documentation.  manufacturer has said he will include directions and i would also encourage him to update the photos on amazon with more examples of how this can be used.  the wood quality is indeed good and it's a sturdy little stand.  i'm trying to think of when i'd actually use this stand... perhaps for facetime chats.  i also think it would be useful for someone in an open office environment if they want to keep their phone on their desk and see alerts / notifications easi

3. Let's continue with punctuation and stop word removal. Stop words are words like "and", "the", etc. They are usually very common words that have little to do with the actual content matter. There's plenty openly available lists of stop words for almost any (natural) language.

* <span style="background-color: #ccfff2">Punctuation and stop-word removal</span>: Let's now remove all punctuation, as well as the stop words. You can find a stop word list for English, e.g. [here](https://gist.github.com/xldrkp/4a3b1a33f10d37bedbe0068f2b4482e8#file-stopwords-en-txt).*(use the link to download a txt of english stopwords)* Save the stopwords in the file as "stopwords-en.txt".

First review at this point reads as: 

*'wrote review manufacturer contacted explained current picture amazon phone vertically stand phone horizontally'*

In [16]:
import string


# Use this cell for your code
def remove_stopwords(text_array):
    with open("stopwords-en.txt", 'r', encoding='utf-8') as f:
        stopwords = f.read().split()
    processed_text = []
    punctuation_remover = str.maketrans("", "", string.punctuation)
    for text in text_array:
        words = text.translate(punctuation_remover).split()
        filtered_words = [w for w in words if w not in stopwords]
        processed_text.append(" ".join(filtered_words))
    return processed_text
data = remove_stopwords(data)
print(data[0])

wrote review manufacturer contacted explained current picture amazon phone vertically stand phone horizontally charge sync cable hole charge landscape position stand sense upgrading review 2 stars 4 stars rarely case user error star lack documentation manufacturer include directions encourage update photos amazon examples wood quality good sturdy stand stand facetime chats open office environment phone desk alerts notifications easily hope updated review helps original review throwing stand garbage crafted nice wood functional instructions product description confusing english translated chinese iphone sits stand fine stand plug plug stand blocks turn iphone plug strange hole stand supposed included plastic feet instructions affixed stand began wobble figure work post review concerned box experience terrible recommend sample exchange honest review


4. Let's continue with stemming. For example, while the words "swims" and "swim" are different strings, they both refer to swimming. [Stemming](https://en.wikipedia.org/wiki/Stemming) refers to the process of mapping words from their inflected form to their base form, for instance: swims -> swim.

* <span style="background-color: #ccfff2">Stemming</span>: Apply a stemmer on the paragraphs, so that inflected forms are mapped to the base form. For example, for Python the popular natural language toolkit [nltk](http://www.nltk.org/howto/stem.html) has an easy to use stemmer. In case you are using R, you can try the [Snowball stemmer](https://www.rdocumentation.org/packages/corpus/versions/0.10.2/topics/stem_snowball). You can find out how to install nltk from [here](https://www.nltk.org/install.html). It will take a while to run! So, grab a coffee and wait :D

Finally, after stemming: 

*'wrote review manufactur contact explain current pictur amazon phone vertic stand phone horizont'*

In [17]:
# Use this cell for your code
import nltk
from nltk.stem import PorterStemmer

def stemming(text_array):
    stemmer = PorterStemmer()
    processed_text = []
    punctuation_remover = str.maketrans("", "", string.punctuation)
    for text in text_array:
        words = text.translate(punctuation_remover).split()
        filtered_words = [stemmer.stem(w) for w in words]
        processed_text.append(" ".join(filtered_words))
    return processed_text
data = stemming(data)
print(data[0])

wrote review manufactur contact explain current pictur amazon phone vertic stand phone horizont charg sync cabl hole charg landscap posit stand sens upgrad review 2 star 4 star rare case user error star lack document manufactur includ direct encourag updat photo amazon exampl wood qualiti good sturdi stand stand facetim chat open offic environ phone desk alert notif easili hope updat review help origin review throw stand garbag craft nice wood function instruct product descript confus english translat chines iphon sit stand fine stand plug plug stand block turn iphon plug strang hole stand suppos includ plastic feet instruct affix stand began wobbl figur work post review concern box experi terribl recommend sampl exchang honest review


5. Finally, filter the data by selecting reviews where the field <span style="background-color: #ccfff2">overall</span> is 4 or 5, and store the review texts in a file named <span style="background-color: #ccfff2">pos.txt</span>. Similarly, select reviews with rating 1 or 2 and store them in a file named <span style="background-color: #ccfff2">neg.txt</span>. Ignore the reviews with overall rating 3. Each line in the two files should contain exactly one preprocessed review text without the rating.

In [18]:
# Use this cell for your code
overall = []
with open('Automotive_5.json', 'r', encoding='utf-8') as f:
    for line in f:
        line = line.strip()
        line = json.loads(line)
        reviewText = line.get("reviewText")
        if reviewText is not None:
            overall.append(line.get("overall"))

pos_reviews = []
neg_reviews = []

for rating,review in zip(overall,data):
    if rating in [4,5]:
        pos_reviews.append(review)
    if rating in [1,2]:
        neg_reviews.append(review)

with open("pos.txt","w",encoding='utf-8') as f:
    for review in pos_reviews:
        f.write(review.strip()+"\n")

with open("neg.txt","w",encoding='utf-8') as f:
    for review in neg_reviews:
        f.write(review.strip()+"\n")



## Exercise 3 | SQL basics

Next, let's take a refresher on the basics of SQL. In this exercise, you will be working on the simplified Northwind 2000 SQLite database. You can download the database from Kaggle [here](https://courses.mooc.fi/api/v0/files/course/f92ffc32-2dd4-421d-87f3-c48800422cc5/files/VEKX2bxGCDGyojG902gmYZTXCnrAQw.zip).

To test your SQL queries and complete the exercise, you can download and install SQLite if you don't yet have it installed.

Please write SQL queries for the tasks on the simplified Northwind 2000 SQLite database.

1. List the first name, last name, and hire date of all employees hired after January 1st, 1994.

2. Count how many orders each customer has placed.

3. Find the names of all customers who have ordered the product "Chai".

4. Find all orders that have been placed but not yet shipped.

5. Find the customer who has placed the most orders.

**Remember to submit your solutions. You can return this Jupyter notebook (.ipynb) or .py, .R, etc depending on your programming preferences. Remember to also submit your SQL queries. No need to submit the text files for the programming exercises.**

In [18]:
# 1

import sqlite3

conn = sqlite3.connect("northwind2000-simplified.sqlite")

cursor = conn.cursor()

cursor.execute("SELECT FirstName, LastName, HireDate FROM Employees where HireDate > '1994-01-01';")
tables = cursor.fetchall()
print(tables)

cursor.close()
conn.close()

[('Robert', 'King', '1994-01-02'), ('Laura', 'Callahan', '1994-03-05'), ('Anne', 'Dodsworth', '1994-11-15')]


In [9]:
# 2

import sqlite3

conn = sqlite3.connect("northwind2000-simplified.sqlite")

cursor = conn.cursor()

cursor.execute("SELECT CustomerID,count(*) FROM orders group by CustomerID;")
tables = cursor.fetchall()
print(tables)

cursor.close()
conn.close()

[('ALFKI', 6), ('ANATR', 4), ('ANTON', 7), ('AROUT', 13), ('BERGS', 18), ('BLAUS', 7), ('BLONP', 11), ('BOLID', 3), ('BONAP', 17), ('BOTTM', 14), ('BSBEV', 10), ('CACTU', 6), ('CENTC', 1), ('CHOPS', 8), ('COMMI', 5), ('CONSH', 3), ('DRACD', 6), ('DUMON', 4), ('EASTC', 8), ('ERNSH', 30), ('FAMIA', 7), ('FOLIG', 5), ('FOLKO', 19), ('FRANK', 15), ('FRANR', 3), ('FRANS', 6), ('FURIB', 8), ('GALED', 5), ('GODOS', 10), ('GOURL', 9), ('GREAL', 11), ('GROSR', 2), ('HANAR', 14), ('HILAA', 18), ('HUNGC', 5), ('HUNGO', 19), ('ISLAT', 10), ('KOENE', 14), ('LACOR', 4), ('LAMAI', 14), ('LAUGB', 3), ('LAZYK', 2), ('LEHMS', 15), ('LETSS', 4), ('LILAS', 14), ('LINOD', 12), ('LONEP', 8), ('MAGAA', 10), ('MAISD', 7), ('MEREP', 13), ('MORGK', 5), ('NORTS', 3), ('OCEAN', 5), ('OLDWO', 10), ('OTTIK', 10), ('PERIC', 6), ('PICCO', 10), ('PRINI', 5), ('QUEDE', 9), ('QUEEN', 13), ('QUICK', 28), ('RANCH', 5), ('RATTC', 18), ('REGGC', 12), ('RICAR', 11), ('RICSU', 10), ('ROMEY', 5), ('SANTG', 6), ('SAVEA', 31), (

In [19]:
# 3

import sqlite3

conn = sqlite3.connect("northwind2000-simplified.sqlite")

cursor = conn.cursor()

cursor.execute("SELECT ContactName FROM Customers c INNER JOIN Orders o ON o.CustomerID = c.CustomerID WHERE o.OrderID in (SELECT OrderID FROM OrderDetails od INNER JOIN Products p on p.ProductID = od.ProductID WHERE ProductName = 'Chai');")
tables = cursor.fetchall()
print(tables)

cursor.close()
conn.close()

[('Horst Kloss',), ('Paula Wilson',), ('Fran Wilson',), ('Rita Müller',), ('Guillermo Fernández',), ('Yang Wang',), ('Lúcia Carvalho',), ('Annette Roulet',), ('Isabel de Castro',), ('Renate Messner',), ('Pirkko Koskitalo',), ('Miguel Angel Paolino',), ('Jean Fresnière',), ('Janine Labrune',), ('Zbyszek Piestrzeniewicz',), ('Frédérique Citeaux',), ('Patricia McKenna',), ('Christina Berglund',), ('Horst Kloss',), ('Jose Pavarotti',), ('Felipe Izquierdo',), ('Simon Crowther',), ('Felipe Izquierdo',), ('Jose Pavarotti',), ('Carlos Hernández',), ('Hari Kumar',), ('Paula Parente',), ('José Pedro Freyre',), ('Elizabeth Lincoln',), ('Paula Parente',), ('Liu Wong',), ('Matti Karttunen',), ('Howard Snyder',), ('Pirkko Koskitalo',), ('Jose Pavarotti',), ('Pascale Cartrain',), ('Ann Devon',), ('Renate Messner',)]


In [20]:
# 4

import sqlite3

conn = sqlite3.connect("northwind2000-simplified.sqlite")

cursor = conn.cursor()

cursor.execute("SELECT * FROM Orders WHERE OrderDate IS NOT NULL and ShippedDate IS NULL")
tables = cursor.fetchall()
print(tables)

cursor.close()
conn.close()

[(11008, 'ERNSH', 7, '1998-04-08 00:00:00.000', '1998-05-06 00:00:00.000', None, 3, 79.46), (11019, 'RANCH', 6, '1998-04-13 00:00:00.000', '1998-05-11 00:00:00.000', None, 3, 3.17), (11039, 'LINOD', 1, '1998-04-21 00:00:00.000', '1998-05-19 00:00:00.000', None, 2, 65), (11040, 'GREAL', 4, '1998-04-22 00:00:00.000', '1998-05-20 00:00:00.000', None, 3, 18.84), (11045, 'BOTTM', 6, '1998-04-23 00:00:00.000', '1998-05-21 00:00:00.000', None, 2, 70.58), (11051, 'LAMAI', 7, '1998-04-27 00:00:00.000', '1998-05-25 00:00:00.000', None, 3, 2.79), (11054, 'CACTU', 8, '1998-04-28 00:00:00.000', '1998-05-26 00:00:00.000', None, 1, 0.33), (11058, 'BLAUS', 9, '1998-04-29 00:00:00.000', '1998-05-27 00:00:00.000', None, 3, 31.14), (11059, 'RICAR', 2, '1998-04-29 00:00:00.000', '1998-06-10 00:00:00.000', None, 2, 85.8), (11061, 'GREAL', 4, '1998-04-30 00:00:00.000', '1998-06-11 00:00:00.000', None, 3, 14.01), (11062, 'REGGC', 4, '1998-04-30 00:00:00.000', '1998-05-28 00:00:00.000', None, 2, 29.93), (1106

In [31]:
# 5

import sqlite3

conn = sqlite3.connect("northwind2000-simplified.sqlite")

cursor = conn.cursor()

cursor.execute("SELECT Customers.CustomerID,ContactName FROM Orders INNER JOIN Customers on Orders.CustomerID = Customers.CustomerID GROUP BY Orders.CustomerID ORDER BY count(*) DESC limit 1;")
tables = cursor.fetchall()
print(tables)

cursor.close()
conn.close()

[('SAVEA', 'Jose Pavarotti')]
